Q1.Deleting Observations with Missing values

In [9]:
import numpy as np
features=np.array([[1.1,11.1],[2.2,22.2],[3.3,33.3],[4.4,44.4],[np.nan,55]])
features

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3],
       [ 4.4, 44.4],
       [ nan, 55. ]])

In [10]:
import pandas as pd
dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])
dataframe.dropna()


feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4

Q2.Imputing Misiing values

We have two methods :
1.KNN
2.SCIKIT

KNN IS MORE BENEFICIAL WHEN WE HAVE NOT MILLIONS OF DATA.I GIVES ALMOST ACCURATE RESULT BUT SCIKIT LEARN GET USEFUL IN MIILIONS OF DATA BUT GIVE WORSE RESULTS THAN KNN

In [14]:
import numpy as np
from fancyimpute import KNN
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

In [24]:
features, _ = make_blobs(n_samples = 1000,n_features = 2,random_state = 1)
true_value = standardized_features[0,0] 
standardized_features[0,0] = np.nan
# Predict the missing values in the feature 

In [26]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

features_mean_imputed = imputer.fit_transform(features)

print(features_mean_imputed)


[[-3.05837272  4.48825769]
 [-8.60973869 -3.72714879]
 [ 1.37129721  5.23107449]
 ...
 [-1.91854276  4.59578307]
 [-1.79600465  4.28743568]
 [-6.97684609 -8.89498834]]


Q3.You have a feature with nominal classes that has no intrinsic ordering (e.g., apple, pear, banana). 

In [27]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer,MultiLabelBinarizer


In [28]:
feature=np.array([["Texas"],["California"],["Texas"],["Delaware"],["Texas"]])
feature

array([['Texas'],
       ['California'],
       ['Texas'],
       ['Delaware'],
       ['Texas']], dtype='<U10')

In [30]:
one_hot=LabelBinarizer()
one_hot.fit_transform(feature)
one_hot.classes_

array(['California', 'Delaware', 'Texas'], dtype='<U10')

If we want to reverse the one-hot encoding, we can use inverse_transform:


In [31]:
one_hot.inverse_transform(one_hot.transform(feature))


array(['Texas', 'California', 'Texas', 'Delaware', 'Texas'], dtype='<U10')

In [33]:
multiclass= [("Texas", "Florida"),("California", "Alabama"),("Texas", "Florida"),("Delware", "Florida"),("Texas", "Alabama")]
one_hot_encode=MultiLabelBinarizer()
one_hot_encode.fit_transform(feature)
one_hot_encode.classes_

array(['California', 'Delaware', 'Texas'], dtype=object)

Q4.You have an ordinal categorical feature (e.g., high, medium, low). 

1.   List item
2.   List item



In [36]:
dataframe=pd.DataFrame({"Score":["Low","Low","Medium","Medium","Barely more than medium","High"]})
scale_mapper={
    "Low":1,"Medium":2,"Barely more than medium":2.5,"High":3
}
dataframe["Score"].replace(scale_mapper)

0    1.0
1    1.0
2    2.0
3    2.0
4    2.5
5    3.0
Name: Score, dtype: float64

Q5.You have a dictionary and want to convert it into a feature matrix. 

In [39]:
from sklearn.feature_extraction import DictVectorizer
data_dict=[{"Red":2,"Blue":4},{"Red":3,"Blue":0},{"Red":2,"Yellow":2}]


In [40]:
dicti=DictVectorizer(sparse=False)
features=dicti.fit_transform(data_dict)


In [41]:
features

array([[4., 2., 0.],
       [0., 3., 0.],
       [0., 2., 2.]])

In [44]:
feature_names = dicti.get_feature_names()
feature_names

['Blue', 'Red', 'Yellow']

In [46]:
pd.DataFrame(features,columns=feature_names)

Blue  Red  Yellow
0   4.0  2.0     0.0
1   0.0  3.0     0.0
2   0.0  2.0     2.0