Q1. You need to create a vector

In [1]:
import numpy as np
vector_row=([1,2,3])
vector_col=np.array([[1],[2],[3]])


Q2. You need to create a Matrix

In [2]:
import numpy as np
matrix=np.array([[1,2],[3,4],[5,6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

Q3. Given data with very few nonzero values, you want to efficiently represent it. 

In [5]:
import numpy as np
from scipy import sparse
matrix=np.array([[0,0],[0,1],[1,3]])
matrix
matrix_sparse=sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	1
  (2, 1)	3


Q4.You need to select one or more elements in a vector or matrix.


In [11]:
import numpy as np
vector=([1,2,3])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[1,1]
vector[2]

3

Q5.Slicing

In [12]:
vector[:]

[1, 2, 3]

In [13]:
vector[1:]

[2, 3]

In [14]:
vector[:1]

[1]

In [15]:
vector[-1:]

[3]

In [16]:
vector[:-1]

[1, 2]

In [18]:
matrix[:1,:]
# selects first row and all cols

array([[1, 2, 3]])

In [23]:
matrix[1:2,:]

array([[4, 5, 6]])

In [22]:
matrix[:,1:2]
# select all rows and the second columns

array([[2],
       [5],
       [8]])

Q6.You want to describe the shape, size, and dimensions of the matrix

In [27]:
import numpy as np
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,1,2,0]])
matrix.shape

(3, 4)

In [28]:
matrix.size

12

In [29]:
matrix.ndim

2

In [31]:
# Use of lambda function
x=lambda a:a+9
print(x(5))

14


Q7.You want to apply some function to multiple elements in an array.


In [30]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
add_100=lambda i:i+100
vectorized=np.vectorize(add_100)
vectorized(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

NumPy’s vectorize class converts a function into a function that can apply to all elements in an array or slice of an array. It’s worth noting that vectorize is essentially a for loop over the elements and does not increase performance. Furthermore, NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same (a process called broadcasting). For example, we can create a much simpler version of our solution using broadcasting:


In [32]:
matrix+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

Q8.You need to find the maximum or minimum value in an array. 

In [33]:
import numpy as np
matrix=([[1,2],[3,4],[5,6]])
np.max(matrix)

6

In [34]:
np.min(matrix)

1

In [36]:
np.max(matrix,axis=0)

array([5, 6])

Q9.You want to calculate some descriptive statistics about an array

In [40]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.mean(matrix)

5.0

In [39]:
np.var(matrix)

2.9166666666666665

In [ ]:
np.std(matrix)

Q10.You want to change the shape (number of rows and columns) of an array without changing the element values. 

In [45]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
matrix.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
matrix.size

12

In [49]:
matrix.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [47]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Q11.You need to transpose a vector or matrix. 

In [51]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Q11.You need to transform a matrix into a one-dimensional array

In [59]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

alternative,use of reshape

In [60]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Q12.You need to know the rank of a matrix. 

In [61]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[11,28,90]])
np.linalg.matrix_rank(matrix)


3

Q13.You need to know the determinant of a matrix

In [66]:
import numpy as np
matrix=([[3,8],[4,6]])
np.linalg.det(matrix)
# 3x6-4x8=18-32=-14

-14.000000000000004

Q14.You need to get the diagonal elements of a matrix. 

In [70]:
matrix = np.array([[1, 2, 3],[2, 4, 6],[3, 8, 9]])
matrix.diagonal()


array([1, 4, 9])

In [72]:
np.fliplr(matrix).diagonal()
# horizontal flip

array([3, 4, 3])

Q15.You need to calculate the trace of a matrix. 

In [73]:
matrix.trace()
# sum of diagnols elements

14

In [74]:
sum(matrix.diagonal())

14

Q16.You need to find the eigenvalues and eigenvectors of a square matrix

In [76]:
import numpy as np
matrix=np.array([[1,-1,3],[1,1,6],[3,8,9]])
eigenvalues,eigenvectors=np.linalg.eig(matrix)
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [77]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

Q17.You need to calculate the dot product of two vectors. 

In [78]:
import numpy as np
vector_a=np.array([1,2,3])
vector_b=np.array([4,5,6])
np.dot(vector_a,vector_b)

32

Q18.You want to calculate the inverse of a square matrix. 

In [79]:
np.linalg.inv(matrix)

array([[ 1.18181818, -1.        ,  0.27272727],
       [-0.27272727, -0.        ,  0.09090909],
       [-0.15151515,  0.33333333, -0.06060606]])

Q19.You want to generate pseudorandom values

In [84]:
np.random.seed(0)
np.random.random(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [83]:
np.random.randint(0,11,3)

array([2, 4, 7])