IMPORTING NUMPY 

In [0]:
import numpy as np

FIXED-TYPE ARRAYS IN PYTHON

In [1]:
import array
L=list(range(10))
A=array.array('i',L)
A
# i is used for indicating integers....

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Now using numpy...creating array from python lists

In [3]:
import numpy as np
np.array([1,4,2,5])

array([1, 4, 2, 5])

In [4]:
np.array([1.4,5,6,7,8])

array([1.4, 5. , 6. , 7. , 8. ])

Tw0 -dimensional array

In [5]:
np.array([range(t,t+3) for t in [2,4,6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

creating arrays from scratch

In [6]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# fill 3 by 5 matrix with 3.15 values...
np.full((3,5),3.15)

array([[3.15, 3.15, 3.15, 3.15, 3.15],
       [3.15, 3.15, 3.15, 3.15, 3.15],
       [3.15, 3.15, 3.15, 3.15, 3.15]])

***creating an array filled with a linear sequence starting at 0, ending at 20,stepping by 2***

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

creat an array of five values evenly spaced between 0 and 1

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

create an 3x3 matrix array of uniformly distributes random values between 0 and 1

In [11]:
np.random.random((3,3))

array([[0.29333148, 0.75262059, 0.19104868],
       [0.73653681, 0.60099739, 0.33121645],
       [0.77263559, 0.98983633, 0.38501247]])

create a 3x3 matrix of normally distributed random values with mean 0 and standard deviation 1

In [12]:
np.random.normal(0,1,(3,3))

array([[ 1.00919713,  0.84668892, -0.45029454],
       [ 0.13942575,  1.09436739,  0.77433435],
       [ 0.65869065, -0.35313369,  0.366594  ]])

create a 3x3 matrix indentity matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

NUMPY STANDARD DATA TYPES

In [14]:
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

NUMPY ARRAY ATTRIBUTES

https://www.geeksforgeeks.org/random-seed-in-python/


DETAILED DESCRIPTION OF RANDOM.SEED()

In [15]:
  import numpy as np
  np.random.seed(0)
  x1=np.random.randint(10,size=6)
  x1

array([5, 0, 3, 3, 7, 9])

In [17]:
#  two dimensional array  
x2=np.random.randint(10,size=(3,4))
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

***ARRAY INDEXING***

https://www.w3schools.com/python/numpy_array_indexing.asp

Better understanding and practice..visit this link.

In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [19]:
x1[0]

5

In [20]:
x1[4]

7

to index from the end of the array ,you can use negative values

In [21]:
x1[-1]

9

In [22]:
x1[-2]

7

In [24]:
# Take all the elements except...?
# x[start:stop:step]

NameError: ignored

In [28]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x[:5] 
# first five elements

array([0, 1, 2, 3, 4])

In [30]:
x[5:]
# last five elements

array([5, 6, 7, 8, 9])

In [31]:
x[1:6:2]

array([1, 3, 5])

In [32]:
x[:-1]
# in this all the elemnets are visible except the last element.

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
x[1::2]

array([1, 3, 5, 7, 9])

IMP. concept asked in interview..reversing.

In [35]:
x[::-1]
# reverse of array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
x[5::-2]
# reverse every other from index 5

array([5, 3, 1])

***MULTIDIMENSIONAL ARRAYS***

In [37]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [39]:
x2[:2,:3]
# two rows,three cols

array([[3, 5, 2],
       [7, 6, 8]])

In [40]:
x2[:3,::2]
# all rows,every other cols

array([[3, 2],
       [7, 8],
       [1, 7]])

In [41]:
x2[:2,::3]

array([[3, 4],
       [7, 8]])

In [0]:
# finally whole matrix is reversed together

In [43]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

Accessing rows and columns

In [44]:
print(x2[:,0])
# printing first column

[3 7 1]


In [46]:
print(x2[0,:])
# printing first row

[3 5 2 4]


In [47]:
print(x2[:2,:2])
# extract 2x2 subarray from this

[[3 5]
 [7 6]]


Modify the array

In [49]:
x2_sub=x2[:2,:2]
x2_sub[0,0]=99
x2_sub

x2_sub[0,1]=97
x2_sub

array([[99, 97],
       [ 7,  6]])

RE-SHAPING OF ARRAYS

Another useful type of operation is reshaping of arrays,The most flexible way of doing this is with the reshape() method. if i want to insert numbers 1 to 9 in 3x3 grid,then do this:

In [51]:
grid=np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**SOME USEFUL TIPS TO REMEMBER.....**

In [52]:
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [0]:
# linspace function that receives as an argument that number of element that we want.Similar like arange

In [53]:
from numpy import pi
np.linspace(0,2,9)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])